home:
  path: /
  defaults: { _controller: "AppBundle:Anime:home" }




formulaire_genre:
  path: /formulaireGenre
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

formulaire_genre_update:
  path: /formulaireGenre/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

liste_genre:
  path: /listeGenre
  defaults: { _controller: "AppBundle:Anime:listeGenre" }

delete_genre:
  path: /deleteGenre/{id}
  defaults: { _controller: "AppBundle:Anime:deleteGenre"}



formulaire_type_anime:
  path: /formulaireTypeAnime
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

formulaire_type_anime_update:
  path: /formulaireTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

liste_type_anime:
  path: /listeTypeAnime
  defaults: { _controller: "AppBundle:Anime:listeTypeAnime" }

delete_type_anime:
  path: /deleteTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:deleteTypeAnime" }



liste_theme:
  path: /listeTheme
  defaults: { _controller: "AppBundle:Anime:listeTheme" }

formulaire_theme:
  path: /formulaireTheme
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTheme" }

formulaire_theme_update:
  path: /formulaireTheme/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTheme" }

delete_theme:
  path: /deleteTheme/{id}
  defaults: { _controller: "AppBundle:Anime:deleteTheme" }



liste_anime:
    path: /listeAnime
    defaults: { _controller: "AppBundle:Anime:listeAnime" }

formulaire_anime:
  path: /formulaireAnime
  defaults: { _controller: "AppBundle:Anime:addAndUpdateAnime" }

formulaire_anime_update:
  path: /formulaireAnime/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateAnime" }

delete_Anime:
  path: /deleteAnime/{id}
  defaults: { _controller: "AppBundle:Anime:deleteAnime" }



liste_saison:
  path: /listeSaison
  defaults: { _controller: "AppBundle:Anime:listeSaison" }

formulaire_saison:
  path: /formulaireSaison
  defaults: { _controller: "AppBundle:Anime:addAndUpdateSaison" }

formulaire_saison_update:
  path: /formulaireSaison/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateSaison" }

delete_Saison:
  path: /deleteSaison/{id}
  defaults: { _controller: "AppBundle:Anime:deleteSaison" }



liste_episode:
  path: /listeEpisode
  defaults: { _controller: "AppBundle:Anime:listeEpisode" }

formulaire_episode:
  path: /formulaireEpisode
  defaults: { _controller: "AppBundle:Anime:addAndUpdateEpisode" }

formulaire_episode_update:
  path: /formulaireEpisode/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateEpisode" }

delete_Episode:
  path: /deleteEpisode/{id}
  defaults: { _controller: "AppBundle:Anime:deleteEpisode" }



liste_article:
  path: /listeArticle
  defaults: { _controller: "AppBundle:Anime:listeArticle" }

formulaire_article:
  path: /formulaireArticle
  defaults: { _controller: "AppBundle:Anime:addAndUpdateArticle" }

formulaire_article_update:
  path: /formulaireArticle/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateArticle" }

delete_Article:
  path: /deleteArticle/{id}
  defaults: { _controller: "AppBundle:Anime:deleteArticle" }