home:
  path: /
  defaults: { _controller: "AppBundle:Anime:home" }

formulaire_genre:
  path: /formulaireGenre
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

formulaire_genre_update:
  path: /formulaireGenre/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

liste_genre:
  path: /listeGenre
  defaults: { _controller: "AppBundle:Anime:listeGenre" }

delete_genre:
  path: /deleteGenre/{id}
  defaults: { _controller: "AppBundle:Anime:deleteGenre"}

formulaire_type_anime:
  path: /formulaireTypeAnime
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

formulaire_type_anime_update:
  path: /formulaireTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

liste_type_anime:
  path: /listeTypeAnime
  defaults: { _controller: "AppBundle:Anime:listeTypeAnime" }

delete_type_anime:
  path: /deleteTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:deleteTypeAnime" }

liste_theme:
  path: /listeTheme
  defaults: { _controller: "AppBundle:Anime:listeTheme" }

formulaire_theme:
  path: /formulaireTheme
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTheme" }

formulaire_theme_update:
  path: /formulaireTheme/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTheme" }

delete_theme:
  path: /deleteTheme/{id}
  defaults: { _controller: "AppBundle:Anime:deleteTheme" }