formulaire_genre:
  path: /formulaireGenre
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

formulaire_genre_update:
  path: /formulaireGenre/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

liste_genre:
  path: /listeGenre
  defaults: { _controller: "AppBundle:Anime:listeGenre" }

formulaire_type_anime:
  path: /formulaireTypeAnime
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

formulaire_type_anime_update:
  path: /formulaireTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

liste_type_anime:
  path: /listeTypeAnime
  defaults: { _controller: "AppBundle:Anime:listeTypeAnime" }