home:
  path: /
  defaults: { _controller: "AppBundle:Anime:home" }


formulaire_genre:
  path: /redacteur/formulaireGenre
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

formulaire_genre_update:
  path: /redacteur/formulaireGenre/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateGenre" }

liste_genre:
  path: /redacteur/listeGenre
  defaults: { _controller: "AppBundle:Anime:listeGenre" }

delete_genre:
  path: /redacteur/deleteGenre/{id}
  defaults: { _controller: "AppBundle:Anime:deleteGenre"}



formulaire_type_anime:
  path: /redacteur/formulaireTypeAnime
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

formulaire_type_anime_update:
  path: /redacteur/formulaireTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTypeAnime" }

liste_type_anime:
  path: /redacteur/listeTypeAnime
  defaults: { _controller: "AppBundle:Anime:listeTypeAnime" }

delete_type_anime:
  path: /redacteur/deleteTypeAnime/{id}
  defaults: { _controller: "AppBundle:Anime:deleteTypeAnime" }



liste_theme:
  path: /redacteur/listeTheme
  defaults: { _controller: "AppBundle:Anime:listeTheme" }

formulaire_theme:
  path: /redacteur/formulaireTheme
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTheme" }

formulaire_theme_update:
  path: /redacteur/formulaireTheme/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateTheme" }

delete_theme:
  path: /redacteur/deleteTheme/{id}
  defaults: { _controller: "AppBundle:Anime:deleteTheme" }



liste_anime:
    path: /redacteur/listeAnime
    defaults: { _controller: "AppBundle:Anime:listeAnime" }

formulaire_anime:
  path: /redacteur/formulaireAnime
  defaults: { _controller: "AppBundle:Anime:addAndUpdateAnime" }

formulaire_anime_update:
  path: /redacteur/formulaireAnime/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateAnime" }

delete_Anime:
  path: /redacteur/deleteAnime/{id}
  defaults: { _controller: "AppBundle:Anime:deleteAnime" }



liste_saison:
  path: /redacteur/listeSaison
  defaults: { _controller: "AppBundle:Anime:listeSaison" }

formulaire_saison:
  path: /redacteur/formulaireSaison
  defaults: { _controller: "AppBundle:Anime:addAndUpdateSaison" }

formulaire_saison_update:
  path: /redacteur/formulaireSaison/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateSaison" }

delete_Saison:
  path: /redacteur/deleteSaison/{id}
  defaults: { _controller: "AppBundle:Anime:deleteSaison" }



liste_episode:
  path: /redacteur/listeEpisode
  defaults: { _controller: "AppBundle:Anime:listeEpisode" }

formulaire_episode:
  path: /redacteur/formulaireEpisode
  defaults: { _controller: "AppBundle:Anime:addAndUpdateEpisode" }

formulaire_episode_update:
  path: /redacteur/formulaireEpisode/{id}
  defaults: { _controller: "AppBundle:Anime:addAndUpdateEpisode" }

delete_Episode:
  path: /redacteur/deleteEpisode/{id}
  defaults: { _controller: "AppBundle:Anime:deleteEpisode" }